# Generated by Django 2.1 on 2020-03-27 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Command',
        ),
    ]
