# Generated by Django 2.1 on 2020-03-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_delete_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='port',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
